sudo: required
services:
- docker
before_install:
- docker pull arxivvanity/engrafo:latest
- docker build -t arxivvanity/engrafo:latest -t arxivvanity/engrafo:${TRAVIS_COMMIT}
  --cache-from arxivvanity/engrafo:latest .
script:
# pass all of the envvars for percy
- docker run -e PERCY_TOKEN -e PERCY_PROJECT -e TRAVIS_BUILD_ID -e TRAVIS_COMMIT -e TRAVIS_PULL_REQUEST_BRANCH -e TRAVIS_BRANCH -e TRAVIS_REPO_SLUG -e TRAVIS_PULL_REQUEST -e TRAVIS_BUILD_NUMBER arxivvanity/engrafo jest
deploy:
  provider: script
  script: script/ci-deploy
  on:
    branch: master
env:
  global:
  # DOCKER_USERNAME
  - secure: "g1Y+cZLqPQ4HZRd22yJH15eivNkYvdP+wjlB9P3ZlZnRaJ/I2bK8bOh/IJPvKJ1ciMwHHcVt/sB9upgbpP+XRqLNTee7jRA3j4qIF1mobkJK63Lawfbv242arTttBK/eXWhmf+QQiyBTGMj+tu/l3LRVY1hizg+j48UpkjRR5kSmuhRA/IVUeTJXpW0Y32+q/zc3xhSLJp7vdhYwiJbFnFKG1Er2MkxJ0GpQonyAyDHCo/XsNPGHciB7VR+mKx4oQoluGPJAQyW1m6MmRlrQw+ddsUS+zuThmQcWzjXwr6BHon4VbiyO+OjTfdguuZlAoKS48MAAwaHvrogoB6oRPJcBgxFmLlJCIp0en+5+V8H7+SlWCftOORs5Uyr0h3SAR0sGyEO5epd1PZ+A9ZfTb/0OGcy5o0pbtjtiOirF1pDboTdCOpzsgvF19ArkrnZzloENpgk/vVDebmoJ8I75Uep1KBP2kNJHabaq+LbpLwypXjd3iGq0BQ6ga8GIbPzZt8Kc0xO7uamtazFoOGi6ZRv1sjLJ0IjATOv8o+Wu/LJ1W8++GdLdQAesiRx8E1rSK9vZofGrUfSq0Nlx1Lq/oqkrDHH0twXldhmcpjOyqKfBr8K020rweCYEwHJnHKPgS6E5IPXrcXIYQhqicC2ctbos/oHwSbvIsejD8PQIpUE="
  # DOCKER_PASSWORD
  - secure: "rPNRZo+Jw2hFSPZFOGhdzkZttzXirp6Spaxs/9XyPs08sOnJe350WwpOuW3qDHUXYIcDqhozCzycrdCv1MCxXcmA3KcKZSQKeLIj2EI0Y6ozfErQUZ9fPNXo5YI868h0YlZeo79HaPrLEwL+iHcyvuK0eMM3QduHBRcXWIC8PqmIAP31lpAlYIcTs1TOKALY79JARh0l4cKWeWCyQcLkRxa80Ov7FqOJtUAOdPgE+AZJX0iMb1a3IZN5S/0MgAtXes+WnrjffBNlEcMjcaXs32KuUfnYHo4QhD8AVmPXPOCTaOBZAhRLAq/23uNVsvBOxTzrIavurG8zKFqcmb1UKD2VO3/thBbDOUkJwr5qoIpRtaVUbl2wcgRf6Ph8V570YatGU98jyJkGS5vxMY+LRIOnEveeNsRUsmAikl1yGgzPIk/aIwQPJp4xy7GctnfiixSkseUJJOkFj+/yYXzC2gs5U8J5u/yrtm5I/AeGgVt0h5JdiyaINBBaKllGzvC8A705LVbn82OBUkmekGwHl7lX9rTyhADOGNcTgfeGTenwhFxsLCaTnnd/DjtEJUGUXdV/kl2R1qM8gR/POQJUMq6yIQzrphCD+AvN8d/+FlqzGMfYtBbV7ei+XXzWfHmg85bUNLn37FSOghsYbnlhNfDZjjI0na9/7B8QpsJZNjU="
